Unroll recursion in _wrapValue test function
The recursive version was throwing errors due to too-deep recursion when
I ran tests with php 5.6.37:

> Fatal error: Maximum function nesting level of '256' reached, aborting! in Unknown on line 0

This change unrolls the recursion as I believe the goal of the test is
to see how `$span->infof()` handles printing a hugely-nested array.